# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  myproject: 'WORK PROGRAM V2/Backend_UMR_Work_Program\Backend_UMR_Work_Program.csproj'
  

steps:
settings
- task: UseDotNet@2
   inputs:
    packageType: 'sdk'
    version: '6.0.x'

settings
- task: DotNetCoreCLI@2
  displayName: 'Publishing App---'
  inputs:
      command: 'Publish'
      publishWebProjects: false
      projects: $(myproject)
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: false
      modifyOutputPath: false
- task: MSBuild@1
  inputs:
    solution: 'WKP_Database/WKP_Database.sqlproj'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
settings
- task: PublishBuildArtifacts@1
   displayName: 'Publishing Build Artifacts---'