CREATE TABLE [dbo].[CompanyProfile]
(
	[Id] INT           IDENTITY (1, 1) NOT NULL,
    [user_Id] NVARCHAR(MAX) NULL, 
    [name] NVARCHAR(MAX) NULL, 
    [business_Type] NVARCHAR(MAX) NULL, 
    [registered_Address_Id] INT NULL, 
    [operational_Address_Id] INT NULL, 
    [affiliate] NVARCHAR(MAX) NULL, 
    [nationality] NVARCHAR(MAX) NULL, 
    [contact_FirstName] NVARCHAR(MAX) NULL, 
    [contact_LastName] NVARCHAR(MAX) NULL, 
    [contact_Phone] NVARCHAR(MAX) NULL, 
    [year_Incorporated] INT NULL, 
    [rC_Number] NVARCHAR(MAX) NULL, 
    [tin_Number] NVARCHAR(MAX) NULL, 
    [no_Staff] INT NULL, 
    [no_Expatriate] INT NULL, 
    [total_Asset] NVARCHAR(MAX) NULL, 
    [yearly_Revenue] NVARCHAR(MAX) NULL, 
    [accident] INT NULL, 
    [accident_Report] NVARCHAR(MAX) NULL, 
    [training_Program] NVARCHAR(MAX) NULL, 
    [mission_Vision] NVARCHAR(MAX) NULL, 
    [hse] NVARCHAR(MAX) NULL, 
    [hseDoc] NVARCHAR(MAX) NULL, 
    [date] DATETIME NULL, 
    [isCompleted] BIT NULL, 
    [elps_Id] INT NULL, 
    [parentCompanyId] INT NULL, 
    [isAffiliate] BIT NULL,
    CONSTRAINT [PK_CompanyProfile] PRIMARY KEY CLUSTERED ([Id] ASC)
)
