CREATE TABLE [dbo].[TypeOfPayments]
(
	[Id] INT IDENTITY (1, 1) NOT NULL, 
    [Name] NVARCHAR(50) NOT NULL, 
    [Category] NVARCHAR(50) NULL,
    CONSTRAINT [PK_TYPEOFPAYMENTS] PRIMARY KEY CLUSTERED ([ID] ASC)
)
